name: reusable workflow
on:
    workflow_call: 
     inputs:
       image-name:
         description: 'Name of the image'
         type: string
         required: true
       image-tag:
         description: 'Tag for the image'
         type: string
         required: true
       dockerfile-path:
         description: 'file path of dockerfile'
         type: string
         required: true         
     secrets:
        registry-username:
           description: 'Username for Docker registry '
           required: true
        registry-password:
          description: 'Password for Docker registry'
          required: true
jobs:
 docker_build:
          runs-on: ubuntu-latest
          name: Building Docker Image  
          steps:
           -
            name: Build Docker image
            run: docker build -t ${{ inputs.image-name }}:${{ inputs.image-tag }} ${{ inputs.dockerfile-path }}
           - 
            name: Log in to Docker Hub
            run: docker login --username ${{ secrets.registry-username }} --password ${{ secrets.registry-password }}
           - 
             name: Push Docker image
             run: docker push ${{ inputs.image-name }}:${{ inputs.image-tag }}

  
