name: reusable workflow
on:
    workflow_call: 
     inputs:
       image-name:
         description: 'Name of the image'
         type: string
         required: true
       image-tag:
         description: 'Tag for the image'
         type: string
         required: true
     secrets:
        registry-username:
           description: 'Username for Docker registry '
           required: true
        registry-password:
          description: 'Password for Docker registry'
          required: true
jobs:
 docker_build:
          runs-on: ubuntu-latest
          name: Building Docker Image  
          steps:
           -
            name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.registry-username }}
              password: ${{ secrets.registry-password }}  
           -
              name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3   
           - 
            name: Build and push Docker image
            run: |
                  docker build -t ${{ secrets.registry-username }}/${{ inputs.image-name }}:${{ inputs.image-tag }} .
                  docker push ${{ secrets.registry-username }}/${{ inputs.image-name }}:${{ inputs.image-tag }}
  
